### ISSUE TITLE
Something wron with action/ic_face

### ISSUE THREAD

**Issue by torgash-ivanblch** [intrications/material-design-icons-adt-template#4]
There's a nice face icon in this set. But in the plugin it's present as ic_faceunlocked but there's no resource for such a name. If I change name back to ic_face in template.xml, then it appears in plugin but isn't loaded,  with ic_3d_rotation loaded instead. Please fix it.

**Comment by intrications** [comment]
Turns out the icon name was changed around the time I released the library.

I've updated the template. Please update your copy of the git repo, making sure that the material-design-icons git submodule is also updated - probably best to just follow the instructions from scratch.

Let me know if you have any problems.

**Comment by torgash-ivanblch** [comment]
Thanks much, you do a great job. There are also some icons that don't show in the plugin window when chosen in list. I can't check them out at the moment, but they are somewhere in the middle of the list.

**Comment by intrications** [comment]
@torgash-ivanblch 

The icons list is being created with a script from the actual image files so it's probably some parsing problem.

Let me know if you notice any that are missing and I'll take a look.
